name: Docker Scout Scan

on:
  push:
    branches:
      - main

jobs:
  docker-scout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: dage5500/suju #suju is my cat I HAD to include her somehow :)
